from easydict import EasyDict as edict

CFG = edict()

CFG.CLASSES_NUMS = 5990
CFG.DATASET_DIR = '/home/oushu/lixingyu/git_repo/attention_OCR/Dataset'
CFG.MAX_SEQ_LEN = 10
CFG.NUM_LSTM_UNITS = 256
CFG.LSTM_STATE_CLIP_VAL = 10.0
CFG.BATCH_SIZE = 32
CFG.LEARNING_RATE = 0.1
CFG.LR_DECAY_STEPS = 50000
CFG.LR_DECAY_RATE = 0.9
CFG.TRAIN_STEPS = 1500000
CFG.DISPLAY_STEP = 10
CFG.SAVE_STEP = 1000